### ISSUE TITLE
Final report peer review

### ISSUE THREAD

**Issue by kdea020** [UOA-MEDSCI-736/nbir012-diptera-morpho#10]
## What was good
- What is currently there in your introduction is really great. Concise overview of morphometrics and even incomplete I can see how the statistical analysis produced by your program contributes to the field. Well done!
- Cool and concise project title that describes the function, purpose and value of your software.
- Like that you've used the Unlicence! Don't know much about it, but a brief read of their website makes it seem like a great choice for your project. And definitely upholding open-science principles :)
## What could be improved
- Your report is obviously in the early stages so not too much to say here! This is really more advice/suggestions than critique, and what you've got is great so far.
- It looks like you're heading that way, but an explanation of what tpsRelw32 does would probably be helpful for the reader.
- An explanation of why wing venation is a useful landmark for morphometrics (and what that is - assume it's veins in the wings!) would also likely help a layman (or software researcher!) understand the purpose and value of the measurement. 
- And you will probably want to cite a paper or other resource (i.e. website/git/etc.) for tpsRel32w so that curious readers can learn a bit more.
- If you keep going with your R code and get that all sorted, I suggest you include a rationale for why you needed that above and beyond Python (i.e. justify the extra installation, dependencies, potential for error and incompatibility). Once again I suspect you were already going to include this and I'm just telling you what you're already writing haha.

(This is not part of the peer review, but figured I may as well offer an early editing pass since there's not much to comment on yet!)
Some spelling and grammar notes:
- You have "derived" twice in the title
- Anotomical -> Anatomical (beginning of first paragraph)
- analagous - anologous (little further down)
- No need for comma after programme (in sentence about tpsRelw32)

**Comment by nbir012** [comment]
Thanks, Kieran - I have run through and made those changes. I am planning to change the tps stuff to MorphoJ which I have a nice citation for.

Cheers again, 

Neil

**Comment by kdea020** [comment]
Changes are looking good. Happy to give you the coveted final handshake.

Good luck with the final submission and your future endeavours Neil :)
