### ISSUE TITLE
Final_assignment_peer_review

### ISSUE THREAD

**Issue by Adamthe1st** [UOA-MEDSCI-736/nbir012-diptera-morpho#11]
Dear Neil, 
# What I liked
- You have included your field of study and the university name under the paper author and affiliations. I think I will do the same as it looks clearer/more organized this way. Well done!
- You have summarized nice overview of your topic ''morphometrics'. You have clearly stated the issue with traditional morphometrics and how geometric morphometrics overcome the previous limitations and how your software contributes to the field. Great job.  
# What could be improved at this stage
- I see that you included the biological keywords which is fantastic. Perhaps try add in code-related keywords like python, open source etc..
- A definition of "tpsRelw32" would make it easier to follow the last part of the introduction. 
- Great use of a figure to deliver your ideas. However, in addition to mentioning that the figure was obtained from an openly available data, you could mention the license in which the figure is under. Eg. CC0 or CC-BY etc. 

Good luck with the rest of the report Neil! Do let me know if you would like me to further review it later today or tonight. 

Best wishes. 

Ahemd

**Comment by nbir012** [comment]
Thanks Adam,

Those are valid points and I have made the changes now. In regards to the figure, it was one that I created from someone's open data and for this reason I believe that my overall copyright will apply to it (the unlicence).

Thanks again,
Neil

**Comment by Adamthe1st** [comment]
Hi Neil, oh sorry I i didnt realize that you had generated the figure yourself. Well done. I had another  look at your changes and I think your documents is sound. Good luck my friend. 

I will close the issue now. 

Cheers Ahmed.
