### ISSUE TITLE
Peer review of code for Neil

### ISSUE THREAD

**Issue by kdea020** [UOA-MEDSCI-736/nbir012-diptera-morpho#3]
## What I liked
- Script is mostly well-commented.
- Code is compact and efficient. Functions are straightforward and each completes a distinct task. Great! 
## What needs improvement
- (Line 11) You might like to make your names more descriptive than "array" - perhaps something like "CleanedData = []" as that indicates what will be inside the array.
- (L 15-17) Could do with comments to describe what is being done here, especially how the strings are being joined.
- (L 21) I'm not sure about this one 'cos I don't know much about python's scoping practice, but since you've used "path" starting from line 4, isn't it best to declare/init the value of "path" before you use it in function csv_writer?

**Comment by nbir012** [comment]
Thanks Kieran,
- L11: I have changed array to tps_array as this will contain the info from the tps file.
- L15-17: notes added
- L21: I've moved L21 to L4. Both seem to work but I would suspect it is good coding practice to define it before it is mentioned.

I've done a pull request with the changes so if you are happy with the changes made, feel free to close this. Please note the file is now located in a folder named 'Code'.

Cheers,

Neil

**Comment by kdea020** [comment]
Those are all great, nicely done. Closing the issue now :)
