### ISSUE TITLE
Peer review of (write-tps-to-csv.py)

### ISSUE THREAD

**Issue by Adamthe1st** [UOA-MEDSCI-736/nbir012-diptera-morpho#5]
Hi Neil, 
Great piece of coding you got here. 
- I liked how you are describing the code as you write it. I found that helpful to follow your code. 
- I see you are doing some looping. This is great as I am at the stage of looping in my own project. I now have a feel of how looping looks like :)
- Although Manish has mentioned it, just a reminder to maybe use the relative path for (line 12) instead of the absolute path. This will make your code readable by any machine as all the files needed will be in your repository. 

Overall, great work overall Neil, keep it up :)

**Comment by nbir012** [comment]
Hey Adam,

Thanks for the feedback, I have done as Manish and yourself have suggested and done a pull request to update this. 

When you have checked this and it is to your satisfaction, please feel free to close the issue.

Toodles,

Neil

**Comment by Adamthe1st** [comment]
Hi Neil, 
Great job my friend! your code looks great. I will close the issue now :) 
Please let me know if you would like me to peer rev future changes too.

Cheers 
Ahmed.
