### ISSUE TITLE
DMP peer review

### ISSUE THREAD

**Issue by BibianaLee** [UOA-MEDSCI-736/nbir012-diptera-morpho#8]
Hi Neil, 

Here's your really late DMP feedback :) 

I think in an overall sense you covered everything you needed to and you stated how you were going to address areas you were unsure about. 
- Your data collection/ creation section was comprehensive and detailed which is good - your "what data will you create/collect" section probably needs updating - I think you've decided to convert all your files to csv now?
- You may want to be explicit about whose google drive, cloud storage etc. you will be utilizing 
- Also when you write the related policies remember to write down which sections of the policy are relevant to your project (I forgot to do this in my DMP). 

I think once you clean it up, update it and fill in the missing information it'll look good! 

Hope that helped
Kind Regards, 

Bibiana

**Comment by nbir012** [comment]
Ahoy Bibiana,

I have made the changes you suggested in the DMP, they are valid points.

If you are happy with everything, please feel free to close this issue.

Toodles,

Neil

**Comment by BibianaLee** [comment]
Hey Neil, 
I'm happy with the changes you've made and will now close the issue :)
