### ISSUE TITLE
DMP peer review

### ISSUE THREAD

**Issue by kdea020** [UOA-MEDSCI-736/nbir012-diptera-morpho#9]
## What was good
- Great detail and outline of the technical requirements of the project, especially the format of files
- Your section on long-term preservation shows clear consideration of how you may achieve this and what needs to be done - good on you for acknowledging the limited lifetime of the proprietary file format!
- Overall great plan that gives me confidence in the safety of your data :+1: 
## What could be improved
- Your description is nicely detailed and does give an overview of the project, but feels like it is written for someone involved in the project rather than an outside audience. This is mostly from the structure (questions and a numbered list) and style of address (use of "I" and "you"). A minor restructure and re-write of some sentences would communicate the goals and design needs of the project more clearly
- Can see that Policies and Guidance is still under construction :) Good idea to link to the applicable university guidelines in addition to your own when you finish this section.
- Could use more detail on how and where the data will be published - will this be the complete data? Raw or processed? And as graphs, tables, or something else?

**Comment by nbir012** [comment]
Thanks for the feedback,

I have made changes based on your comments and pushed the new document to my dev branch. 
If you are happy with the changes please feel free to close the issue. 

Cheers,

Neil

**Comment by kdea020** [comment]
Looks great Neil. Closing the issue and good luck with your report!
